export const IMG_SRC: {[name:string]: string} = {
    chanelle: "https://static.wikia.nocookie.net/survivor/images/c/cb/S42_chanelle_t.png",
    daniel: "https://static.wikia.nocookie.net/survivor/images/9/97/S42_daniel_t.png",
    drea: "https://static.wikia.nocookie.net/survivor/images/9/95/S42_drea_t.png",
    hai: "https://static.wikia.nocookie.net/survivor/images/2/29/S42_hai_t.png",
    jackson: "https://static.wikia.nocookie.net/survivor/images/b/bb/S42_jackson_t.png",
    jenny: "https://static.wikia.nocookie.net/survivor/images/6/6a/S42_jenny_t.png",
    jonathan: "https://static.wikia.nocookie.net/survivor/images/c/c8/S42_jonathan_t.png",
    lindsay: "https://static.wikia.nocookie.net/survivor/images/d/d7/S42_lindsay_t.png",
    lydia: "https://static.wikia.nocookie.net/survivor/images/9/93/S42_lydia_t.png",
    marya: "https://static.wikia.nocookie.net/survivor/images/1/1b/S42_marya_t.png",
    maryanne: "https://static.wikia.nocookie.net/survivor/images/2/26/S42_maryanne_t.png",
    mike: "https://static.wikia.nocookie.net/survivor/images/c/c7/S42_mike_t.png",
    omar: "https://static.wikia.nocookie.net/survivor/images/8/86/S42_omar_t.png",
    rocksroy: "https://static.wikia.nocookie.net/survivor/images/2/2c/S42_rocksroy_t.png",
    romeo: "https://static.wikia.nocookie.net/survivor/images/0/09/S42_romeo_t.png",
    swati: "https://static.wikia.nocookie.net/survivor/images/3/3b/S42_swati_t.png",
    tori: "https://static.wikia.nocookie.net/survivor/images/2/24/S42_tori_t.png",
    zach: "https://static.wikia.nocookie.net/survivor/images/d/db/S42_zach_t.png",
};
